#!/bin/bash
USER=anvart
THIS_HOST=$(hostname)
AGGREGATOR_HOST=claudio06

NODE_HOME=/home/slurm/$USER-${SLURM_JOB_ID}
NODE_CONF=$NODE_HOME/conf

CONF_DIR=$PROJECT_HOME/conf
DISTR_DIR=$PROJECT_HOME/distr
NODE_LOG_DIR=$PROJECT_HOME/logs/$THIS_HOST

NODE_TMP_DIR=$NODE_HOME/tmp
NODE_VENV_DIR=$NODE_HOME/venv

DEPENDENCIES_DIR=$PROJECT_HOME/dependencies
APACHE_DIR=$DEPENDENCIES_DIR/apache

VIRTUALENV_DIR=$DEPENDENCIES_DIR/venv

COLLECTD_DIR=$DEPENDENCIES_DIR/collectd
STORMWATCH_DIR=$DEPENDENCIES_DIR/stormwatch
NODE_COLLECTD_DIR=$NODE_HOME/collectd
NODE_COLLECTD_LOG_FILE=$NODE_LOG_DIR/collectd.log

GRAPHITE_API_CONFIG=$NODE_VENV_DIR/conf/graphite-api.yaml

NIMBUS_MOCK_PORT=8888
