#!/bin/sh
#SBATCH --job-name=setup-stormwatch
#SBATCH --partition=kraken_fast
#SBATCH --nodes=1
#SBATCH --output=slurm.out

PROJECT_HOME=/home/user/anvart/stormwatch

NODE_GRAPHITE="claudio06"
NODE_ALL="claudio[06-07]"

srun --ntasks-per-node=1 --nodes=1 $PROJECT_HOME/scripts/jobs/node/setup.sh $PROJECT_HOME

